version: "3"

services:
  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#      - "8080:80"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  shop:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg/shop
    ports:
      - "5050:5000"
    volumes:
      - ./:/app
    depends_on:
      - pg

  shop-prod:
    build:
      context: .
      dockerfile: docker-build/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg/shop
    ports:
      - "5080:80"
    depends_on:
      - pg

#  pg-old:
#    image: postgres:9 # use latest official postgres version
#    environment:
#      POSTGRES_DB: blog
#      POSTGRES_PASSWORD: qwer234r
#    ports:
#      - "5433:5432"

#
#  mariadb:
#    image: mariadb:10.8 # use latest official postgres version

volumes:
  pg-data:


